name: CI/CD Pipeline nhacCuaToi
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and deploy
        id: deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST_NHACCUATOI}}
          username: ${{ secrets.EC2_USER_NHACCUATOI }}
          key: ${{ secrets.EC2_KEY_NHACCUATOI }}
          port: 22
          script_stop: true
          export_outputs: true
          script: |
            set -e
            cd /home/${{ secrets.EC2_USER_NHACCUATOI }}/nhacCuaToi
            {
              git pull origin main
              sudo docker compose -f docker-compose.yml down --volumes --rmi all
              sudo docker system prune -a -f
              sudo docker compose -f docker-compose.yml up -d --build
            } 2>&1 | tee deploy_escaped.log

      - name: Copy log file deploy_escaped.log from ec2 to run_number
        run: |
          scp -i ${{ secrets.EC2_KEY_NHACCUATOI }} \
            -o StrictHostKeyChecking=no \
            ${{ secrets.EC2_USER_NHACCUATOI }}@${{ secrets.EC2_HOST_NHACCUATOI }}:/home/${{ secrets.EC2_USER_NHACCUATOI }}/nhacCuaToi/deploy_escaped.log \
            ./deploy_escaped.log

      - name: Send email notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.GMAIL_USER }}
          password: ${{ secrets.GMAIL_APP_PASS }}
          subject: ${{ steps.deploy.outcome }} - Deployment nhacCuaToi
          to: "${{ secrets.GMAIL_USER }}"
          from: "nhacCuaToi <${{ secrets.GMAIL_USER }}>"
          html_body: |
            <html>
              <body>
                <h2>Deployment nhacCuaToi</h2>
                <p>Job name: <b>${{ github.job }}</b></p>
                <p>Repository: <b>${{ github.repository }}</b></p>
                <p>Branch: <b>${{ github.ref }}</b></p>
                <p>Commit: <b>${{ github.sha }}</b></p>
                <p>Author: <b>${{ github.actor }}</b></p>
                <p>Workflow: <b>${{ github.workflow }}</b></p>
                <p>Run number: <b>${{ github.run_number }}</b></p>
                <p>Run ID: <b>${{ github.run_id }}</b></p>

                <p>Status: 
                  <b style="color: ${{ job.status == 'success' && 'green' || 'red' }}">
                    ${{ job.status }}
                  </b>
                </p>

                <hr>
                <h3>The detailed log is attached</h3>
              </body>
            </html>
          attachments: deploy_escaped.log
